ProjetoES/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('filtros.urls')),
    path('', include('testes.urls')),
    path('', include('filtros.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testes/urls.py
from django.urls import path
from .views import  showimage
# from .views import UploadCreate

urlpatterns = [
    #Exemplo: path('', IndexView.as_view(), name='inicio'),
    # path('', showimage, name="upload-imagem"),
    path('testes/upload/', showimage, name="upload-imagem"),
    # path('testes/', UploadCreate.as_view(), name="imagem"),
]

testes/models.py
from django.db import models
from .utils import get_filtered_image
from PIL import Image
import numpy as np
from io import BytesIO
from django.core.files.base import ContentFile

# Create your models here.
# ACTION_CHOICES = (
#     ('NO_FILTER', 'no filter'),
#     ('COLORIZED', 'colorized'),
#     ('GRAYSCALE', 'grayscale'),
#     ('BLURRED', 'blurred'),
#     ('BINARY', 'binary'),
#     ('INVERT', 'invert'),
# )

class Image(models.Model):
    # name= models.CharField(max_length=500)
    imagefile= models.FileField(upload_to='uploads/', null=True, verbose_name="")
    # action = models.CharField(max_length=50, choices=ACTION_CHOICES, verbose_name='Ação', help_text='Aqui você coloca um texto')
    # description = models.CharField(max_length=60, verbose_name='Descrição da imagem')

    # def __str__(self):
    #     return self.name + ": " + str(self.imagefile)


class Result(models.Model):
    # name= models.CharField(max_length=500)
    imagefile= models.FileField(upload_to='uploads/', null=True, verbose_name="")
    code_name = models.CharField(max_length=50)
    code_pk = models.PositiveIntegerField()
    # action = models.CharField(max_length=50, choices=ACTION_CHOICES, verbose_name='Ação', help_text='Aqui você coloca um texto')
    # description = models.CharField(max_length=60, verbose_name='Descrição da imagem')

    # def __str__(self):
    #     return self.name + ": " + str(self.imagefile)

# class Upload(models.Model):
#     image = models.ImageField(upload_to='uploads', verbose_name='Imagem')
    
#     action = models.CharField(max_length=50, choices=ACTION_CHOICES, verbose_name='Ação', help_text='Aqui você coloca um texto')
#     description = models.CharField(max_length=60, verbose_name='Descrição da imagem')

#     def __str__(self):
#         return f"[{self.pk}]"
#         # return f"[{self.pk}] {self.description}"

#     def save(self, *args, **kwargs):

#          # open image
#          pil_img = Image.open(self.image)

#          # convert the image to array and do some processing
#          cv_img = np.array(pil_img)
#         #  img = get_filtered_image(cv_img, self.action)
#          img=cv_img

#          # convert back to pil image
#          im_pil = Image.fromarray(img)

#          # save
#          buffer = BytesIO()
#          im_pil.save(buffer, format='png')
#          image_png = buffer.getvalue()

#          self.image.save(str(self.image), ContentFile(image_png), save=False)

#          super().save(*args, **kwargs)

testes/views.py
# from typing import ClassVar
# from django.db import models
# from django.views.generic import TemplateView
from django import forms
from django.shortcuts import render, redirect
# from django.http import HttpResponseRedirect
# from django.views.generic.edit import CreateView
# from django.http import FileResponse
from django.http.response import HttpResponse
# from django.template import RequestContext
# from django.contrib import messages
import re
# from filtros.models import Teste
from filtros.models import Script

from .models import Image, Result
# from .models import Upload

from django.urls import reverse_lazy
import cv2
import mimetypes
import os
from types import SimpleNamespace

# class UploadCreate(CreateView):
#     model = Upload
#     fields = ['image']
#     template_name = 'testes/upload.html'
#     success_url = reverse_lazy('inicio')


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["imagefile"]


def historico():
    hist_path = 'uploads/historico.txt'
    r = '\n'.join([i.code_name for i in Result.objects.all()])
    with open(hist_path, 'w') as file:
        file.write(r)
    path = open(hist_path, 'r')
    mime_type, _ = mimetypes.guess_type(hist_path)
    response = HttpResponse(path, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % 'historico.txt'
    os.remove(hist_path)
    return response


def cont(context):
    categorias = ['imagem', 'limiarização', 'morfologia']
    filtros_sep = [[] for i in range(len(categorias)+1)]
    filtros = [[i.nome, i.pk, i.categoria] for i in Script.objects.filter()]
    for i in filtros:
        if (low := i[2].lower()) in categorias:
            filtros_sep[categorias.index(low)].append(i)
        else:
            filtros_sep[len(categorias)].append(i)
    for count, cat in enumerate(categorias):
        context[cat] = filtros_sep[count]
    context['outros'] = filtros_sep[len(categorias)]
    context['codigo'] = SKPT(last.code_pk).codigo if (
        last := Result.objects.last()) else ''


def save_result(scpt, url_out, pk):
    result = Result()
    result.imagefile.name = url_out[8:]
    result.code_name = scpt.nome
    result.code_pk = pk
    result.save()


def create_file(scpt, url_in, url_out):
    image_in = cv2.imread('.'+url_in)
    image_out = image_in
    loc = locals()
    print(scpt.codigo)
    try:
        exec(scpt.codigo, globals(), loc)
    except:
        pass
    cv2.imwrite('.'+url_out, loc['image_out'])


def last(url):
    if last := Result.objects.last():
        return '/uploads'+last.imagefile.name
    else:
        return url


def SKPT(pk):
    try:
        return Script.objects.filter(pk=pk)[0]
    except:
        print('PK EXCEPTION')
        return SimpleNamespace(nome=False, codigo=False)


def get_form(request):
    form = ImageForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        Result.objects.all().delete()
        form.save()
        return redirect(request.META.get('HTTP_REFERER'))


def showimage(request):
    imagefile = lastimage.imagefile if (
        lastimage := Image.objects.last()) else None

    if(ret := get_form(request)):
        return ret

    url_init = '/uploads/'+imagefile.name
    url_out = ''

    if request.method == 'POST':
        if request.POST.get("historico"):
            return historico()
        if pk := request.POST.get("data"):
            scpt = SKPT(pk)
            url_in = last(url_init)
            url_out = '/uploads/results/_'+url_in.split('/')[-1]
            create_file(scpt, url_in, url_out)
            save_result(scpt, url_out, pk)
            return redirect(request.META.get('HTTP_REFERER'))

    context = {'imagefile': url_init,
               'result_file': last(url_out),
               'filename': imagefile.name[8:] if imagefile else '',
               }
    cont(context)
    print()
    return render(request, 'testes/upload.html', context)

testes/templates/testes/upload.html
{% extends 'paginas/base.html' %} {% load static %} {% load crispy_forms_tags %}
{% block titulo %}
<title>UPLOAD</title>
{% endblock %} {% block conteudo %}

<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  {% block botaoadd %}
  <div>
    <div
      style="
        display: flex;
        flex-direction: row;
        align-items: baseline;
        margin-bottom: 30px;
      "
    >
      <form
        enctype="multipart/form-data"
        action=""
        method="POST"
        class="col-6 pb-2 align-items-left flex-row"
        id="submit_file"
      >
        {% csrf_token %}
        <input
          type="file"
          class="custom-file-input"
          name="imagefile"
          required
          id="id_imagefile"
          data-preview-file-type="text"
        />
        <label
          class="custom-file-label"
          for="id_imagefile"
          id="label_file"
          style="margin-right: 12px;"
        >
          {% if filename %} {{filename}} {% else %} arquivo {% endif %}
        </label>
      </form>
      <div
        style="
          display: flex;
          flex-direction: row;
          align-items: baseline;
          justify-content: space-between;
          gap: 50px;
          margin-left: 120px;
        "
      >
        <div>
          <button class="btn btn-secundary" onclick="exibescript()">
            <i class="fas fa-file-code f15c fa-3x"></i>
          </button>
        </div>
        <div>
          <button class="btn btn-secundary" onclick="exibeconteudo()">
            <i class="fas fa-file-alt f15c fa-3x"></i>
          </button>
        </div>
        <div>
          <form method="post" action="">
            {% csrf_token %}
            <button
              class="btn btn-secundary"
              type="submit"
              name="historico"
              value="historico"
              href="#"
            >
              <span class="fa-stack fa-2x">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fas fa-file-alt fa-stack-1x fa-inverse"></i>
              </span>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script
    src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"
    type="text/javascript"
  ></script>
  <script>
    function exibescript() {
      confirm(
        '{{ codigo|linebreaks }}'
          .replace(/(<br>)/g, '\n')
          .replace(/(<p>|<[/]p>)/g, ''),
      )
    }
    function exibeconteudo() {
      confirm(
        'Teoria: Processamento de Imagens.\nDisponível em: http://www.dpi.inpe.br/spring/teoria/realce/realce.htm.',
      )
      // confirm(
      //   '{{ form.as_p }}'
      // )
    }
    $('#id_imagefile').on('change', function () {
      // console.log('change fire')
      // var i = $('#label_file').clone()
      var file = $('#id_imagefile')[0].files[0].name
      // console.log(file)
      $('#label_file').text(file)
      // console.log(i.text())
      $('#submit_file').submit()
    })
  </script>

  {% endblock %}

  <div class="row">
    <!-- Area Chart -->
    <div class="col-xl-6 col-lg-5">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
        >
          <h6 class="m-0 font-weight-bold text-primary">Imagem Original</h6>
        </div>
        <!-- Card Header - Dropdown -->
        <div
          class="py-0 d-flex flex-row align-items-center justify-content-between"
        >
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Arquivo
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <div
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              <a class="dropdown-item" href="#">Novo</a>
              <a class="dropdown-item" href="#">Abrir</a>
              <a class="dropdown-item" href="#">Recentes</a>
              <a class="dropdown-item" href="#">Salvar</a>
              <a class="dropdown-item" href="#">Salvar como</a>
              <a class="dropdown-item" href="#">Sair</a>
            </div>
          </div>
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Editar
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <div
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              <a class="dropdown-item" href="#">Desfazer</a>
              <a class="dropdown-item" href="#">Copiar</a>
              <a class="dropdown-item" href="#">Recortar</a>
              <a class="dropdown-item" href="#">Colar</a>
            </div>
          </div>
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Imagem
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <form
              method="post"
              action=""
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              {% for i in imagem %} {% csrf_token %}
              <button
                type="submit"
                name="data"
                value="{{i.1}}"
                class="dropdown-item"
                href="#"
              >
                {{i.0}}
              </button>
              {% endfor %}
              <!-- <input type="submit" value="Select"> -->
            </form>
          </div>
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Limiarização
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <form
              method="post"
              action=""
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              {% for i in limiarização %} {% csrf_token %}
              <button
                type="submit"
                name="data"
                value="{{i.1}}"
                class="dropdown-item"
                href="#"
              >
                {{i.0}}
              </button>
              {% endfor %}
              <!-- <input type="submit" value="Select"> -->
            </form>
          </div>
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Morfologia
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <form
              method="post"
              action=""
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              {% for i in morfologia %} {% csrf_token %}
              <button
                type="submit"
                name="data"
                value="{{i.1}}"
                class="dropdown-item"
                href="#"
              >
                {{i.0}}
              </button>
              {% endfor %}
              <!-- <input type="submit" value="Select"> -->
            </form>
          </div>
          <div class="dropdown no-arrow m-2">
            <span class="mr-0 d-none d-lg-inline text-gray-900 small">
              Outros
            </span>
            <a
              class="dropdown-toggle"
              href="#"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-900"></i>
            </a>
            <form
              method="post"
              action=""
              class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink"
            >
              {% for i in outros %} {% csrf_token %}
              <button
                type="submit"
                name="data"
                value="{{i.1}}"
                class="dropdown-item"
                href="#"
              >
                {{i.2}}| {{i.0}}
              </button>
              {% endfor %}
              <!-- <input type="submit" value="Select"> -->
            </form>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-area">
            <div
              style="
                display: table-cell;
                vertical-align: middle;
                text-align: center;
              "
            >
              <style>
                img {
                  position: absolute;
                  max-height: 100%;
                  max-width: 100%;
                }
              </style>
              {% if imagefile %}
              <img src="{{imagefile}}" />
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Area Chart -->
    <div class="col-xl-6 col-lg-5">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
        >
          <h6 class="m-0 font-weight-bold text-primary">Imagem Resultante</h6>

          <ul class="navbar-nav ml-auto">
            <div class="topbar-divider d-none d-sm-block"></div>
          </ul>
        </div>
        <div class="dropdown no-arrow m-2">
          <span class="mr-2 d-none d-lg-inline text-gray-900 small"></span>
          <a
            class="dropdown-toggle"
            href="#"
            role="button"
            id="dropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          ></a>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-area">
            <div
              style="
                display: table-cell;
                vertical-align: middle;
                text-align: center;
              "
            >
              {% if result_file %}
              <img src="{{result_file}}" />
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Content Row -->
    <div class="row"></div>
  </div>
  <!-- /.container-fluid -->
</div>

{% endblock %}